custom_components/daikin_residential_altherma/climate.py
custom_components/daikin_residential_altherma/manifest.json

Would be much cleaner when Home Assistant would provide a separate horizontal and vertical swing for the climate entity, hopefully at some point

Support more swing modes

---

custom_components/daikin_residential_altherma/manifest.json
custom_components/daikin_residential_altherma/select.py

Add support for demandControl

---

custom_components/daikin_residential_altherma/__init__.py
custom_components/daikin_residential_altherma/manifest.json

Fixed integration reload

---

custom_components/daikin_residential_altherma/climate.py
custom_components/daikin_residential_altherma/switch.py

Fix wrong UI refresh

---

custom_components/daikin_residential_altherma/climate.py

* custom_components/daikin_residential_altherma/climate.py:

Set necessary flag for turn_on/turn_off warning

---

custom_components/daikin_onecta/__init__.py
custom_components/daikin_onecta/config_flow.py
custom_components/daikin_onecta/coordinator.py
custom_components/daikin_onecta/daikin_api.py
custom_components/daikin_onecta/diagnostics.py
custom_components/daikin_onecta/strings.json
custom_components/daikin_onecta/translations/en.json

Add OptionsConfig Flow

---

custom_components/daikin_onecta/coordinator.py
custom_components/daikin_onecta/switch.py

* custom_components/daikin_onecta/coordinator.py:
* custom_components/daikin_onecta/switch.py:

Small fixes

---

custom_components/daikin_onecta/icons.json

Add icon translations for fan modes

---

.github/workflows/tests.yaml

* .github/workflows/tests.yaml:

Add codecov

---

custom_components/daikin_onecta/climate.py

Small fix to async_turn_on

---

custom_components/daikin_onecta/climate.py

Changed caching update

---

.github/workflows/tests.yaml
requirements_test.txt
tests/conftest.py
tests/test_config_flow.py

Enable test

---

pyproject.toml
requirements_dev.txt

* pyproject.toml:
* requirements_dev.txt:

Black is not used anymore

---

custom_components/daikin_onecta/climate.py
custom_components/daikin_onecta/daikin_api.py
custom_components/daikin_onecta/device.py
tests/fixtures/holidaymode.json
tests/snapshots/test_init.ambr
tests/test_init.py

Storing work done for #116, ran out of limits for today because of all testing of this morning:
- post has to be tested, some problems returning yet 422
- need to determine start/end dates
- need to update the code to disable holiday mode through a post

Add support for holiday mode

---

custom_components/daikin_onecta/climate.py
custom_components/daikin_onecta/daikin_api.py
custom_components/daikin_onecta/device.py
custom_components/daikin_onecta/select.py
custom_components/daikin_onecta/switch.py
custom_components/daikin_onecta/water_heater.py
readme.md
tests/snapshots/test_init.ambr
tests/test_init.py

* custom_components/daikin_onecta/daikin_api.py:
* custom_components/daikin_onecta/device.py:
* custom_components/daikin_onecta/select.py:
* custom_components/daikin_onecta/switch.py:
* custom_components/daikin_onecta/water_heater.py:

Cleanup of bearerrquest

---

custom_components/daikin_onecta/binary_sensor.py

* custom_components/daikin_onecta/binary_sensor.py:

Remove sub_type, not used in this sensor

---

custom_components/daikin_onecta/climate.py
custom_components/daikin_onecta/device.py
tests/fixtures/altherma3m.json
tests/snapshots/test_init.ambr
tests/test_init.py

Altherma 3M leaving water temperature/offset changes

---

custom_components/daikin_onecta/climate.py
tests/fixtures/ururu.json
tests/snapshots/test_init.ambr
tests/test_init.py

* tests/fixtures/ururu.json:
Added.
* tests/snapshots/test_init.ambr:
* tests/test_init.py:

Map daikin operation mode humidification to dry

---

custom_components/daikin_onecta/water_heater.py
tests/test_init.py

* custom_components/daikin_onecta/water_heater.py:
* tests/test_init.py:

Implement turn_on/turn_off on the water_heater

---

custom_components/daikin_onecta/icons.json

* custom_components/daikin_onecta/icons.json:

Add som more icon settings, fixed #210

---

custom_components/daikin_onecta/water_heater.py
tests/test_init.py

* custom_components/daikin_onecta/water_heater.py:
* tests/test_init.py:

Also test and optimize setting the tank temperature

---

custom_components/daikin_onecta/daikin_api.py

* custom_components/daikin_onecta/daikin_api.py:

In case of an error log the full response text

---

custom_components/daikin_onecta/climate.py
tests/snapshots/test_init.ambr

* tests/snapshots/test_init.ambr:

Only export the hvac modes which can be set or which is current

---

custom_components/daikin_onecta/daikin_api.py

* custom_components/daikin_onecta/daikin_api.py:

Add some more error logging

---

tests/test_init.py

Moved some test code to another method to increase coverage

---

custom_components/daikin_onecta/config_flow.py

* custom_components/daikin_onecta/config_flow.py:

Increase max fequence, fixed discussion 229

---

custom_components/daikin_onecta/water_heater.py

* custom_components/daikin_onecta/water_heater.py:

Water_heater supports on/off, fixed #298

---

custom_components/daikin_onecta/climate.py
tests/fixtures/fanmode.json
tests/snapshots/test_init.ambr
tests/test_init.py

Related to #326, unit test doesn't show a problem, extended logging

Extend logging and added test for checking fanmodes

---

custom_components/daikin_onecta/const.py

* custom_components/daikin_onecta/const.py:

Remove not used constants

---

custom_components/daikin_onecta/sensor.py

* custom_components/daikin_onecta/sensor.py:

Reduce duplicated code

---

.github/workflows/tests.yaml

* .github/workflows/tests.yaml:

Test with multiple python versions

---

.github/workflows/tests.yaml
tests/test_init.py

Test that water_heater state is not updated on a rate limit case

---

tests/test_init.py

Test rate limit on schedule selection

---

custom_components/daikin_onecta/climate.py

Add logging to get hvac mode

---

custom_components/daikin_onecta/config_flow.py

* custom_components/daikin_onecta/config_flow.py:

Increase max ignore time to 300
